version: '3.6'

services:
  influxdb:
    image: influxdb
    container_name: bgx-stats-influxdb
    networks:
    - network1
    ports:
      - '8086:8086'
    volumes:
      - /var/lib/influx-data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=metrics
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=pwadmin
  grafana:
    image: bgx-stats-grafana
    container_name: bgx-stats-grafana
    networks:
    - network1
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    command: |
      bash -c "
        cd app
        /app/grafana_entrypoint.sh
      "
    stop_signal: SIGKILL

networks:
  network1:
     name: bgx-stats-network

