version: '3.6'

services:

  rest-api-a:
    build:
      context: .
      dockerfile: rest_api/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: sawtooth-rest-api-a
    volumes:
      - ./:/project/sawtooth-core
    container_name: rest-api-a
    ports:
      - "8007:8007"
#    networks:
#      - network1

    # depends_on:
    #   - validator
    command: |
      bash -c "
        bin/protogen
        cd rest_api/chilkat-linux
        python3 installChilkat.py
        cd ../
        python3 setup.py clean --all
        python3 setup.py build
        sawtooth-rest-api -vv --connect tcp://18.222.233.160:4004  --bind rest-api-a:8007
      "
    stop_signal: SIGKILL

  web_app:
    build:
      context: web_app_node/
      dockerfile: Dockerfile
    volumes:
      - ./web_app_node:/app
    container_name: web_app
    ports:
      - "8000:8000"
    environment:
      - ENV_VAR
    depends_on:
       - rest-api-a
    command: |
      bash -c "
        npm i
        node index.js
      "
    stop_signal: SIGKILL


networks:
  network1:
     name: bgx-network2
